repos:
  - repo: https://github.com/nixos/nixfmt
    rev: v1.2.0
    hooks:
      - id: nixfmt-nix
        args: [--, --check]
  - repo: local
    hooks:
      - id: statix
        name: statix
        entry: statix check
        language: system
        files: \.nix$
        pass_filenames: false
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        args: [-x, -P, scripts]
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt
        args: [-d]
